#include <iostream>
#include <fstream>
#include <cmath>
#include <vector>
#include "include/ppm.hpp"
#include "include/model.hpp"

using namespace std;

void headerWriter(ofstream &file, int width, int height) {
    file << "P3\n";
    file << width << " " << height << "\n";
    file << "255\n"; 
}

void pixelWriter(ofstream &file, int red, int green, int blue) {
    file << red << " " << green << " " << blue << "\n";
}

// Parte 2
vector<double> interpolate(const vector<double>& A, const vector<double>& B,const vector<double>& C, const vector<double>& D, double u, double v) {
    // P(t) = (1 - t) * A + t * B
    
    vector<double> I_axb = {(1 - u) * A[0] + u * B[0],
                            (1 - u) * A[1] + u * B[1],
                            (1 - u) * A[2] + u * B[2]};

    vector<double> I_cxd = {(1 - u) * C[0] + u * D[0],
                            (1 - u) * C[1] + u * D[1],
                            (1 - u) * C[2] + u * D[2]};

    vector<double> P = {(1 - v) * I_axb[0] + v * I_cxd[0],
                        (1 - v) * I_axb[1] + v * I_cxd[1],
                        (1 - v) * I_axb[2] + v * I_cxd[2]};

    return P;
}

int main() {
    const int width = 400;
    const int height = 200;

    // Random colors generated by gpt
    std::vector<RGBColor> colors = {
        {1.0, 0.0, 0.0}, // Red
        {0.0, 1.0, 0.0}, // Green
        {0.0, 0.0, 1.0}, // Blue
        {1.0, 1.0, 1.0}  // White
    };

    BackgroundColor temp(colors);

    ofstream ppmFile("image.ppm");

    if (!ppmFile.is_open()) {
        cerr << "Error: Unable to open the file." << endl; 
        return 1;
    }

    headerWriter(ppmFile, width, height);

    for (int y = height; y > 0; y--) {
        for (int x = 0; x < width; x++) {
            double u = static_cast<double>(x) / (width - 1);
            double v = static_cast<double>(y - 1) / (height - 1); 

            // Interpolate:
            // vector<double> color = interpolate(A, B, C, D, u, v);
            // pixelWriter(ppmFile, static_cast<int>(color[0]), static_cast<int>(color[1]), static_cast<int>(color[2]));

            // Using background class

            RGBColor newColor = temp.sampleUV(u,v);
            pixelWriter(ppmFile, newColor.r, newColor.g, newColor.b);
        }
    }

    ppmFile.close();

    cout << "Image generated" << endl;

    return 0;
}